// flow-typed signature: 26993f9a43e95de2b0199fc2cb01e97c
// flow-typed version: <<STUB>>/lodash.property_v^4.4.2/flow_v0.97.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'lodash.property'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'lodash.property' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'lodash.property/index' {
  declare module.exports: $Exports<'lodash.property'>;
}
declare module 'lodash.property/index.js' {
  declare module.exports: $Exports<'lodash.property'>;
}
