// flow-typed signature: 43daf0098219a2ed1c14f222d64d63ba
// flow-typed version: <<STUB>>/styled-media-query_v^2.1.1/flow_v0.97.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'styled-media-query'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'styled-media-query' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'styled-media-query/dist/styled-media-query.common' {
  declare module.exports: any;
}

declare module 'styled-media-query/dist/styled-media-query.es' {
  declare module.exports: any;
}

declare module 'styled-media-query/dist/styled-media-query.umd' {
  declare module.exports: any;
}

declare module 'styled-media-query/src/convertors' {
  declare module.exports: any;
}

declare module 'styled-media-query/src/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'styled-media-query/dist/styled-media-query.common.js' {
  declare module.exports: $Exports<'styled-media-query/dist/styled-media-query.common'>;
}
declare module 'styled-media-query/dist/styled-media-query.es.js' {
  declare module.exports: $Exports<'styled-media-query/dist/styled-media-query.es'>;
}
declare module 'styled-media-query/dist/styled-media-query.umd.js' {
  declare module.exports: $Exports<'styled-media-query/dist/styled-media-query.umd'>;
}
declare module 'styled-media-query/src/convertors.js' {
  declare module.exports: $Exports<'styled-media-query/src/convertors'>;
}
declare module 'styled-media-query/src/index.js' {
  declare module.exports: $Exports<'styled-media-query/src/index'>;
}
