// flow-typed signature: 0fbc1c9cbfab2ac0763be03cfbf90049
// flow-typed version: <<STUB>>/stylelint-config-suitcss_v^14.0.0/flow_v0.97.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'stylelint-config-suitcss'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'stylelint-config-suitcss' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'stylelint-config-suitcss/index' {
  declare module.exports: $Exports<'stylelint-config-suitcss'>;
}
declare module 'stylelint-config-suitcss/index.js' {
  declare module.exports: $Exports<'stylelint-config-suitcss'>;
}
